// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoQcDFaP9rABAjtJ4SlU2hHbbGtIZVuTU',
    appId: '1:404974452024:web:9cd9bbc76256a355dfd5cd',
    messagingSenderId: '404974452024',
    projectId: 'recipe-app-1b312',
    authDomain: 'recipe-app-1b312.firebaseapp.com',
    storageBucket: 'recipe-app-1b312.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpBnZd7Fp2UcMtyAklQKPv9O9hIPfrt3Q',
    appId: '1:404974452024:android:542d284314f3f790dfd5cd',
    messagingSenderId: '404974452024',
    projectId: 'recipe-app-1b312',
    storageBucket: 'recipe-app-1b312.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdRGaV3KPoFRg8YcQo4uTx7zzs1vBqMu4',
    appId: '1:404974452024:ios:b42f4321432cd494dfd5cd',
    messagingSenderId: '404974452024',
    projectId: 'recipe-app-1b312',
    storageBucket: 'recipe-app-1b312.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdRGaV3KPoFRg8YcQo4uTx7zzs1vBqMu4',
    appId: '1:404974452024:ios:b42f4321432cd494dfd5cd',
    messagingSenderId: '404974452024',
    projectId: 'recipe-app-1b312',
    storageBucket: 'recipe-app-1b312.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoQcDFaP9rABAjtJ4SlU2hHbbGtIZVuTU',
    appId: '1:404974452024:web:964453b1aa8d6160dfd5cd',
    messagingSenderId: '404974452024',
    projectId: 'recipe-app-1b312',
    authDomain: 'recipe-app-1b312.firebaseapp.com',
    storageBucket: 'recipe-app-1b312.firebasestorage.app',
  );
}
